volumes:
  postgres_data:


services:
  backend:
    build:
      context: ./backend
      dockerfile: .dockerfile
    container_name: finance-backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/www 
      - /app/node_modules
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    container_name: pg-finance
    env_file:
      - ./backend/.env
    ports:
      - 5431:5432
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
