// app/shared/constants/error.constants.ts
export const ERROR_CODES = {
  // Usuário
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_INACTIVE: 'USER_INACTIVE',
  LOGIN_INVALID: 'LOGIN_INVALID',

  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_EMAIL: 'INVALID_EMAIL',
  PASSWORD_INVALID: 'PASSWORD_INVALID',
  INVALID_NAME: 'INVALID_NAME',

  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
} as const;

export const ERROR_MESSAGES = {
  [ERROR_CODES.USER_NOT_FOUND]: 'Usuário não encontrado',
  [ERROR_CODES.USER_ALREADY_EXISTS]: 'Usuário já existe',
  [ERROR_CODES.EMAIL_ALREADY_EXISTS]: 'Email já existe',
  [ERROR_CODES.INVALID_CREDENTIALS]: 'Credenciais inválidas',
  [ERROR_CODES.VALIDATION_ERROR]: 'Erro de validação',
  [ERROR_CODES.INVALID_EMAIL]: 'Você não pode atualizar o email com o mesmo email',
  [ERROR_CODES.INVALID_NAME]: 'Você não pode atualizar o nome com o mesmo nome',
  [ERROR_CODES.LOGIN_INVALID]: 'Email ou senha incorretos',
  [ERROR_CODES.PASSWORD_INVALID]: 'Senha incorreta',
} as const;
